lots of changes, some of them breaking
- safe sudo password passing to expect via an environment variable
- replace plain text vault.yml by lookup via gopass
- add playbook specific vault: `$playbook.vault.yml`
- safe cleanup also on interruption
- variable injection per default into remote script
- inject files root path into remote script: `$W`
- flatten config file key hierarchies
- swap shebang by more portable `/usr/bin/env bash`
- transform all config variables to uppercase to follow shell script conventions (env variables shall be uppercase)
- swap `$cfg_` prefix by `$W_` for config variables
- add playbook specific variables (borrowed by a fork of welder: https://github.com/homelinen/welder)
- only execute one script in each module: ./setup.sh (otherwise scripts in the files subfolder got executed too)
- use vault values in template variabel substitution
- replace ruby by python and thus liquid by jinja2 (the templates remain mostly compatible)
- opt in for sudo password query: `ask_sudo_password: true` (in `$playbook.yml`)
- introduce shell variable escaping for the config values
- … and some more small improvements

diff --git a/libexec/welder-compile b/libexec/welder-compile
--- a/libexec/welder-compile
+++ b/libexec/welder-compile
@@ -1,13 +1,14 @@
 #!/bin/bash
 #
+# Compile all template files and upload all results.
 #
-#
+# TODO: exit rap handler for cleanup
 
-[ -n "$DEBUG" ] && set -v
+set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
+set -o errexit   ## set -e : exit the script if any statement returns a non-true return value
 
-set -eu
 
-source $WELDER_ROOT/libexec/priv/_helpers
+. $WELDER_ROOT/libexec/priv/_helpers
 
 playbook=$1
 [ -z "$playbook" ] && __fail "Usage: x compile <playbook-name>"
@@ -15,50 +16,57 @@ playbook=$1
 __ensure_rsync
 __load_config "$playbook.yml"
 
-tmp_dir=$(pwd)/tmp/setup
+tmp_dir=$(pwd)/tmp
 mkdir -p $tmp_dir
 rm -rf $tmp_dir/*
+
+# add launcher
+cp "${WELDER_ROOT}/libexec/priv/launcher.sh" "${tmp_dir}/launcher.sh"
 
 # rsyncs only the modules that include files/ directories
 # skips setup.sh scripts and creates list of files to be compiled
 # and uploaded to the server
-function __rsync_modules() {
+__rsync_modules() {
   rsync -a --prune-empty-dirs --include="*/" --include="modules/*/files/**" --exclude='*' --quiet ./modules $tmp_dir
 }
 
 # Copy all "files" directories to ./tmp so they can be parsed
-if [ -z "${cfg_shared_path-}" ]; then
+if [ -z "${W_SHARED_PATH-}" ]; then
   echo # do nothing
 else
-  cd $cfg_shared_path && __rsync_modules && cd -
+  cd "$W_SHARED_PATH" && __rsync_modules && cd -
 fi
 
 __rsync_modules
 
-# Compile templates (if there's any *.liquid files)
-if test -n "$(find $tmp_dir -name '*.liquid' -print -quit)"
-then
-  __info "compiling *.liquid templates"
-  $WELDER_ROOT/libexec/priv/compile-templates $tmp_dir
+# fetch secrets from vaults via gopass
+[ -f "vault.yml" ] && __load_secrets "vault.yml" >> "${tmp_dir}/vault.yml"
+[ -f "${playbook}.vault.yml" ] && __load_secrets "${playbook}.vault.yml" >> "${tmp_dir}/vault.yml"
+
+# source: global config
+[ -f "./config.yml" ] && $WELDER_ROOT/libexec/priv/parse-config "config.yml" \
+  >> "${tmp_dir}/config-variables" "export W_"
+# source: global vault
+[ -f "${tmp_dir}/vault.yml" ] && $WELDER_ROOT/libexec/priv/parse-config "${tmp_dir}/vault.yml" "export W_" \
+  >> $tmp_dir/config-variables
+# source: playbook vault via gopass
+[ -f "${tmp_dir}/${playbook}.vault.yml" ] && $WELDER_ROOT/libexec/priv/parse-config "${tmp_dir}/${playbook}.vault.yml" "export W_" \
+  >> $tmp_dir/config-variables
+# source: playbook
+$WELDER_ROOT/libexec/priv/parse-config "$playbook.yml" "export W_" W_MODULES >> $tmp_dir/config-variables
+
+
+# Compile templates (if there are any *.liquid|*.j2 files)
+if test -n "$(find $tmp_dir -name '*.liquid' -o -name "*.j2" -print -quit)"; then
+  __info "compiling templates"
+  $WELDER_ROOT/libexec/priv/compile-templates "$tmp_dir" "config.yml" "${playbook}.yml" "${tmp_dir}/vault.yml"
   __success "compiled templates"
-fi
-
-# Compile yaml config files into shell-compatible variables
-[ -f $tmp_dir/config-variables ] && rm $tmp_dir/config-variables
-
-if [ -f "./config.yml" ]
-then
-  $WELDER_ROOT/libexec/priv/parse-config "./config.yml" > $tmp_dir/config-variables
-fi
-
-if [ -f "./vault.yml" ]
-then
-  $WELDER_ROOT/libexec/priv/parse-config "./vault.yml" >> $tmp_dir/config-variables
 fi
 
 __info "uploading template files to the server"
 
 # rsync compiled files to the server, skipping source (liquid) templates
-rsync -a -e "ssh -p $cfg_ssh_port" --delete --exclude="*.liquid" --quiet $tmp_dir/ $cfg_ssh_url:setup
+rsync --archive --rsh "ssh -p $W_SSH_PORT" --delete --exclude="*.liquid" --exclude="*.j2" --quiet \
+  $tmp_dir/ "${W_SSH_URL}:.welder/"
 
 __success "uploading template files to the server"
diff --git a/libexec/welder-run b/libexec/welder-run
--- a/libexec/welder-run
+++ b/libexec/welder-run
@@ -1,72 +1,84 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Run all jobs of a given playbook.
+set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
+set -o errexit   ## set -e : exit the script if any statement returns a non-true return value
 
-[ -n "$DEBUG" ] && set -v
 
-set -eu
+__run_module() {
+  module="$1"
+  
+  # shared path is defined and local module doesn't exist
+  if [ -n "${W_SHARED_PATH-}" ] && [ ! -d "./modules/$module" ]; then
+    module_path="$W_SHARED_PATH/modules/$module"
+  else
+    module_path="./modules/$module"
+  fi
 
-source $WELDER_ROOT/libexec/priv/_helpers
+  # prepare remote script
+  script_local="${module_path}/setup.sh"
+  script_remote_path=".welder/${module}.sh"
+  scp -qP "$W_SSH_PORT" "$script_local" "${W_SSH_URL}:${script_remote_path}"
+  ssh -qp "$W_SSH_PORT" "$W_SSH_URL" "chmod +x '${script_remote_path}'"
 
-playbook=$1
-[ -z "$playbook" ] && __fail "Usage: x run <playbook-name>"
+  if [ -z ${sudo_pass+x} ]; then
+    # no sudo_pass set, run the script directly
+    ssh -qtp "$W_SSH_PORT" "$W_SSH_URL" ".welder/launcher.sh $module"
+  else
+    # wrap the ssh script with an "expect" script to automatically enter the sudo password
+    command="ssh -t $W_SSH_URL -p $W_SSH_PORT .welder/launcher.sh $module"
+    SUDO_PASS="$sudo_pass" $WELDER_ROOT/libexec/priv/run-ssh-script2 $command
+  fi
+}
+
+# Run all *.sh scripts for each module listed in $playbook
+__run_scripts() {
+  echo
+
+  for module in "${W_MODULES[@]}"; do
+    __info "module '$module'\n"
+
+    __run_module "$module"
+
+    echo
+  done
+}
+
+exit_handler() {
+  if [ $completed = 0 ]; then
+    echo "  …"
+    __warn "execution aborted, cleaning up …"
+  fi
+  
+  welder cleanup $playbook
+  
+  if [ $completed = 1 ]; then
+    __success "all done!"
+  fi
+}
+
+### end: function definitions
+
+completed=0
+trap 'exit_handler' EXIT
+
+. $WELDER_ROOT/libexec/priv/_helpers
+
+playbook="$1"
+[ -z "$playbook" ] && __fail "Usage: welder run <playbook-name>"
 
 __load_config "$playbook.yml"
 
 [ ! -d ./modules ] && __fail "no modules/ directory found"
 
-# Run all *.sh scripts for each module listed in $playbook
-function __run_scripts() {
-  echo
-
-  for module in "${cfg_modules[@]}"
-  do
-    __info "module $module\n"
-
-    if [ -z "${cfg_shared_path-}" ]; then
-      module_path="./modules/$module"
-    else
-      # shared path defined
-      if [ -d "./modules/$module" ]; then
-        # local module should have priority
-        module_path="./modules/$module"
-      else
-        module_path="$cfg_shared_path/modules/$module"
-      fi
-    fi
-
-    for script in $(find $module_path -name "*.sh")
-    do
-      __info "script $script\n"
-
-      if [ -z ${sudo_pass+x} ]
-      then
-        # no sudo_pass set, run the script directly
-        ssh -t "$cfg_ssh_url" -p "$cfg_ssh_port" "$(< $script)"
-      else
-        # wrap the ssh script with an "expect" script to automatically
-        # enter sudo password
-        $WELDER_ROOT/libexec/priv/run-ssh-script "$cfg_ssh_url" "$cfg_ssh_port" "$(< $script)" $sudo_pass
-      fi
-
-      echo
-    done
-
-    echo
-    echo
-  done
-}
-
 welder compile $playbook
 
 # Ask sudo password for non-root users
 # For this to work, ssh_url needs to follow user@server-url format
-if [[ ! $cfg_ssh_url =~ root\@.* ]]
-then
-  __user "what's the sudo password for $cfg_ssh_url: "
+if [ ${W_ASK_SUDO_PASSWORD:-0} = 1 ] && [[ ! $W_SSH_URL =~ root\@.* ]]; then
+  __user "what's the sudo password for $W_SSH_URL: "
   read -se sudo_pass
 fi
 
 __run_scripts
 
-welder cleanup $playbook
-
-__success "all done!"
+completed=1
